import { PLANET_TYPE } from "./planetDataConstants";
import { typeTextureMapOptions } from "./planetTextureClassTypeLayers";
import { SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS } from "./planetDataConstants";

const extraTextureMapOptions: {
  [id: string]: typeTextureMapOptions;
} = {
  largeJaggedLayer: {
    isBumpMap: true,
    layerOpacity: 0.5,
    rangeStart: 0.0,
    rangeEnd: 1.0,
    scale: 2.6,
    octaves: 7,
    amplitude: 3.3,
    persistence: 1.2,
    lacunarity: 0.9,
    isDoubleNoise: true,
    stretchX: 1.7,
    stretchY: 3.7,
    isWarp: false,
    lowAltColor: "#ad0000",
    hightAltColor: "#ea10e2",
    craterIntensity: 0,
  },
  martianDetailLayer1: {
    isBumpMap: true,
    layerOpacity: 0.5,
    rangeStart: 0.3,
    rangeEnd: 1.0,
    scale: 1,
    octaves: 9,
    amplitude: 3.3,
    persistence: 0.8,
    lacunarity: 1.7,
    isDoubleNoise: false,
    isWarp: false,
    lowAltColor: "#aa6666", //starData.colorHex,
    hightAltColor: "#afafaf",
    craterIntensity: 0,
  },
  martianDetailLayer2: {
    isBumpMap: true,
    layerOpacity: 0.5,
    rangeStart: 0.5,
    rangeEnd: 1.0,
    scale: 3,
    octaves: 9,
    amplitude: 3.3,
    persistence: 0.8,
    lacunarity: 1.7,
    isDoubleNoise: false,
    isWarp: true,
    lowAltColor: "#aa6666", //starData.colorHex,
    hightAltColor: "#afafaf",
    craterIntensity: 0,
  },
  cloudDetailLayer1: {
    isBumpMap: true,
    layerOpacity: 0.3,
    rangeStart: 0.0,
    rangeEnd: 1.0,
    scale: 0.4,
    octaves: 6,
    amplitude: 3,
    persistence: 0.6,
    lacunarity: 2.9,
    isDoubleNoise: false,
    isWarp: false,
    lowAltColor: "#000000",
    hightAltColor: "#ffffff",
  },
  cloudDetailLayer2: {
    isBumpMap: true,
    layerOpacity: 0.6,
    rangeStart: 0.0,
    rangeEnd: 1.0,
    scale: 2,
    octaves: 6,
    amplitude: 0.4,
    persistence: 0.6,
    lacunarity: 2.1,
    isDoubleNoise: false,
    isWarp: false,
    lowAltColor: "#000000",
    hightAltColor: "#ffffff",
  },
  riversDetailLayer1: {
    isBumpMap: false,
    isFlipNegative: true,
    layerOpacity: 0.9,
    flatSurfaceNorm: 0.5,
    rangeStart: 0.0,
    rangeEnd: 1.0,
    scale: 4,
    octaves: 9,
    amplitude: 2.3,
    persistence: 0.7,
    lacunarity: 1.9,
    isDoubleNoise: false,
    isWarp: true,
    lowAltColor: "#001933",
    hightAltColor: "#001933",
  },
  mountainDetailLayer1: {
    isBumpMap: true,
    layerOpacity: 0.8,
    rangeStart: 0.3,
    rangeEnd: 1.0,
    scale: 1,
    octaves: 6,
    amplitude: 0.5,
    persistence: 0.8,
    lacunarity: 2.5,
    isDoubleNoise: false,
    isWarp: false,
    lowAltColor: "#808080",
    hightAltColor: "#142608",
  },
};

export const PLANET_TYPE_TEXTURE_LAYERS: {
  [id: number]: typeTextureMapOptions[];
} = {
  [PLANET_TYPE.mterran]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.vegetation[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.water[0],
    extraTextureMapOptions.riversDetailLayer1,
    extraTextureMapOptions.mountainDetailLayer1,
  ],
  [PLANET_TYPE.sterran]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.sand[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.rock[0],
    extraTextureMapOptions.martianDetailLayer1,
    extraTextureMapOptions.martianDetailLayer2,
  ],
  [PLANET_TYPE.terran]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.water[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.vegetation[0],
    extraTextureMapOptions.riversDetailLayer1,
    extraTextureMapOptions.cloudDetailLayer1,
  ],
  [PLANET_TYPE.earthLike]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.water[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.vegetation[0],
    extraTextureMapOptions.riversDetailLayer1,
    extraTextureMapOptions.cloudDetailLayer2,
  ],
  [PLANET_TYPE.suTerran]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.rock[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.sand[0],
    extraTextureMapOptions.martianDetailLayer1,
    extraTextureMapOptions.martianDetailLayer2,
  ],
  [PLANET_TYPE.venusian]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.lava[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.clouds[0],
    extraTextureMapOptions.cloudDetailLayer1,
    extraTextureMapOptions.martianDetailLayer2,
  ],
  [PLANET_TYPE.neptunian]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.gas[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.clouds[0],
    extraTextureMapOptions.cloudDetailLayer1,
    extraTextureMapOptions.cloudDetailLayer2,
  ],
  [PLANET_TYPE.jovian]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.gas[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.clouds[0],
    extraTextureMapOptions.largeJaggedLayer,
    extraTextureMapOptions.cloudDetailLayer2,
  ],
  [PLANET_TYPE.hotJovian]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.lava[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.gas[0],
    extraTextureMapOptions.largeJaggedLayer,
    extraTextureMapOptions.martianDetailLayer2,
  ],
  [PLANET_TYPE.dwarf]: [
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.rock[0],
    SPECIAL_WORLDS_TEXTURE_LAYERS_OPTIONS.ice[0],
    extraTextureMapOptions.martianDetailLayer1,
    extraTextureMapOptions.martianDetailLayer2,
  ],
};
